services:
  # searxng:
  #   image: docker.io/searxng/searxng:latest
  #   volumes:
  #     - ./searxng:/etc/searxng:rw
  #   ports:
  #     - 4000:8080
  #   networks:
  #     - llm-network
  #   restart: unless-stopped

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=https://searxng.codifybites.com
    volumes:
      - backend-dbstore:/home/perplexica/data
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - llm-network
    restart: unless-stopped

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://perplexica-backend:3001/api
        - NEXT_PUBLIC_WS_URL=ws://perplexica-backend:3001
    depends_on:
      - perplexica-backend
    networks:
      - llm-network
    restart: unless-stopped

networks:
  llm-network:


volumes:
  backend-dbstore:
